name: Deploy Javadoc

permissions:
  contents: write
  
on:
  push:
    branches:
      - gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy javadoc to Github Pages
        uses: JulesC0urne/actions-publish-javadoc@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
